# Generated by Django 6.0.2 on 2026-02-07 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('unite', models.CharField(choices=[('UNITE', 'Unité'), ('CARTON', 'Carton'), ('BOITE', 'Boîte'), ('LOT', 'Lot'), ('PAQUET', 'Paquet')], default='UNITE', max_length=20, verbose_name='Unité')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock actuel')),
                ('stock_max', models.IntegerField(default=10, verbose_name='Stock maximum')),
                ('seuil_alerte', models.IntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fourniture',
                'verbose_name_plural': 'Fournitures',
                'ordering': ['type', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='TypeFourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de fourniture',
                'verbose_name_plural': 'Types de fourniture',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='fournitures.fourniture')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='fournitures.fourniture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='fourniture',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='fournitures.typefourniture'),
        ),
    ]
