# Generated by Django 4.2.28 on 2026-02-07 17:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typefourniture',
            options={'ordering': ['nom'], 'verbose_name': 'Type de fourniture', 'verbose_name_plural': 'Types de fourniture'},
        ),
        migrations.AddField(
            model_name='commande',
            name='date_reception',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='commande',
            name='priorite',
            field=models.BooleanField(default=False, verbose_name='Prioritaire'),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='fourniture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='commande_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournitures.commande', verbose_name='Commande liée'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='fournitures.fourniture', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='seuil_alerte',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='stock_max',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock maximum'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournitures', to='fournitures.typefourniture', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='unite',
            field=models.CharField(choices=[('UNITE', 'Unité'), ('CARTON', 'Carton'), ('BOITE', 'Boîte'), ('LOT', 'Lot'), ('PAQUET', 'Paquet'), ('RAMETTE', 'Ramette'), ('STYLO', 'Stylo')], default='UNITE', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='fournitures.fourniture', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='quantite',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=10, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='typefourniture',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du type'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['date_creation'], name='fournitures_date_cr_860864_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['status'], name='fournitures_status_3a5ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['produit'], name='fournitures_produit_18b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='fourniture',
            index=models.Index(fields=['reference'], name='fournitures_referen_c4a8bd_idx'),
        ),
        migrations.AddIndex(
            model_name='fourniture',
            index=models.Index(fields=['type'], name='fournitures_type_id_87dae2_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['date'], name='fournitures_date_a5e9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['produit'], name='fournitures_produit_b478ee_idx'),
        ),
    ]
