# Generated by Django 4.2.28 on 2026-02-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournitures', '0002_alter_typefourniture_options_commande_date_reception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='priorite',
        ),
        migrations.RemoveField(
            model_name='fourniture',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='commande_liee',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_lies', to='fournitures.commande', verbose_name='Commande liée'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name='Type de mouvement'),
        ),
    ]
