# Generated by Django 4.2.28 on 2026-02-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0003_remove_commande_priorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='numero',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AddField(
            model_name='fourniture',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='ancien_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ancien stock'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='nouveau_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nouveau stock'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='reference',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='unite',
            field=models.CharField(choices=[('UNITE', 'Unité'), ('CARTON', 'Carton'), ('BOITE', 'Boîte'), ('LOT', 'Lot'), ('PAQUET', 'Paquet'), ('RAMETTE', 'Ramette')], default='UNITE', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=15, verbose_name='Type de mouvement'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['numero'], name='fournitures_numero_92bf28_idx'),
        ),
        migrations.AddIndex(
            model_name='fourniture',
            index=models.Index(fields=['actif'], name='fournitures_actif_d9b332_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvement',
            index=models.Index(fields=['type_mouvement'], name='fournitures_type_mo_91c924_idx'),
        ),
    ]
