# Generated by Django 4.2.28 on 2026-02-08 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fournitures', '0004_commande_numero_fourniture_actif_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mouvement',
            options={'ordering': ['-date'], 'verbose_name': 'Mouvement', 'verbose_name_plural': 'Mouvements'},
        ),
        migrations.RemoveIndex(
            model_name='mouvement',
            name='fournitures_date_a5e9d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='mouvement',
            name='fournitures_produit_b478ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='mouvement',
            name='fournitures_type_mo_91c924_idx',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='ancien_stock',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='mouvement',
            name='nouveau_stock',
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
