# Generated by Django 4.2.28 on 2026-02-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0005_alter_mouvement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_lies', to='fournitures.commande', verbose_name='Commande associée'),
        ),
    ]
