# Generated by Django 4.2.28 on 2026-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0006_mouvement_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourniture',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Référence'),
        ),
    ]
