# Generated by Django 4.2.28 on 2026-02-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0007_alter_fourniture_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourniture',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fourniture',
            name='reference',
            field=models.CharField(blank=True, help_text="Doit commencer par 'F' (ex: F001). Laisser vide pour générer automatiquement.", max_length=20, null=True, unique=True, verbose_name='Référence'),
        ),
        migrations.AddIndex(
            model_name='fourniture',
            index=models.Index(fields=['stock'], name='fournitures_stock_f27db4_idx'),
        ),
    ]
