# Generated by Django 4.2.28 on 2026-02-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0008_fourniture_date_modification_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commande',
            name='fournitures_date_cr_860864_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='fournitures_status_3a5ab1_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='fournitures_produit_18b2bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='commande',
            name='fournitures_numero_92bf28_idx',
        ),
        migrations.RemoveIndex(
            model_name='fourniture',
            name='fournitures_referen_c4a8bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='fourniture',
            name='fournitures_type_id_87dae2_idx',
        ),
        migrations.RemoveIndex(
            model_name='fourniture',
            name='fournitures_actif_d9b332_idx',
        ),
        migrations.RemoveIndex(
            model_name='fourniture',
            name='fournitures_stock_f27db4_idx',
        ),
    ]
