# Generated by Django 6.0.2 on 2026-02-08 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0009_remove_commande_fournitures_date_cr_860864_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_en_cours',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date mise en cours'),
        ),
        migrations.AddField(
            model_name='commande',
            name='utilisateur_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours de livraison'), ('RECUE', 'Reçue'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
