# Generated by Django 6.0.2 on 2026-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournitures', '0010_commande_date_en_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourniture',
            name='unite',
            field=models.CharField(choices=[('UNITE', 'Unité'), ('unité', 'unité'), ('CARTON', 'Carton'), ('BOITE', 'Boîte'), ('LOT', 'Lot'), ('PAQUET', 'Paquet'), ('RAMETTE', 'Ramette')], default='UNITE', max_length=20, verbose_name='Unité'),
        ),
    ]
